DISCOUNTED_TOTAL_RETURN_INDEX = "discounted_total_return_index"
TOTAL_RETURN_INDEX_LOG_RETURN_MOMENTS = "total_return_index_log_return_moments"

ALL_VALIDATION_ANALYSES = [
    DISCOUNTED_TOTAL_RETURN_INDEX,
    TOTAL_RETURN_INDEX_LOG_RETURN_MOMENTS,
]