AVERAGE_DISCOUNT_FACTOR = "average_discount_factor"
DISCOUNTEd_BOND_INDEX = "discounted_bond_index"
DISCOUNTED_TOTAL_RETURN_INDEX = "discounted_total_return_index"
DISCOUNTED_ZCB = "discounted_zero_coupon_bond"
TOTAL_RETURN_INDEX_LOG_RETURN_MOMENTS = "total_return_index_log_return_moments"

ALL_VALIDATION_ANALYSES = [
    AVERAGE_DISCOUNT_FACTOR,
    DISCOUNTEd_BOND_INDEX,
    DISCOUNTED_TOTAL_RETURN_INDEX,
    DISCOUNTED_ZCB,
    TOTAL_RETURN_INDEX_LOG_RETURN_MOMENTS,
]
